<?xml version="1.0" encoding="UTF-8"?>
<project version="4">
  <component name="ContentModelStore">
    <e p="C:\Users\v.vasilchenko\.Rider2019.1\system\extResources" t="IncludeRecursive" />
    <e p="C:\Users\v.vasilchenko\.Rider2019.1\system\resharper-host\local\Transient\ReSharperHost\v191\SolutionCaches\_AutoCADElectrical.1649661501.00" t="ExcludeRecursive" />
    <e p="D:\Autocad Additional Files\AcadApplications\dotNET\Projects\AutoCADElectrical" t="IncludeFlat">
      <e p="AutoCADElectrical" t="IncludeRecursive">
        <e p="app.config" t="Include" />
        <e p="AutoCADElectrical.vbproj" t="IncludeRecursive" />
        <e p="bin" t="ExcludeRecursive" />
        <e p="default_catDataSet.Designer.vb" t="Include" />
        <e p="default_catDataSet.vb" t="Include" />
        <e p="default_catDataSet.xsc" t="Include" />
        <e p="default_catDataSet.xsd" t="Include" />
        <e p="default_catDataSet.xss" t="Include" />
        <e p="footprint_lookupDataSet.Designer.vb" t="Include" />
        <e p="footprint_lookupDataSet.xsc" t="Include" />
        <e p="footprint_lookupDataSet.xsd" t="Include" />
        <e p="footprint_lookupDataSet.xss" t="Include" />
        <e p="GlobalSuppressions.vb" t="Include" />
        <e p="My Project" t="Include">
          <e p="Application.Designer.vb" t="Include" />
          <e p="Application.myapp" t="Include" />
          <e p="AssemblyInfo.vb" t="Include" />
          <e p="Resources.Designer.vb" t="Include" />
          <e p="Resources.resx" t="Include" />
          <e p="Settings.Designer.vb" t="Include" />
          <e p="Settings.settings" t="Include" />
        </e>
        <e p="obj" t="ExcludeRecursive" />
        <e p="src" t="Include">
          <e p="com" t="Include">
            <e p="vasilchenko" t="Include">
              <e p="Commands.vb" t="Include" />
              <e p="DBAccessConnection" t="Include">
                <e p="DataAccessObject.vb" t="Include" />
                <e p="DatabaseConnection.vb" t="Include" />
                <e p="WiresAdditionalFunctions.vb" t="Include" />
              </e>
              <e p="ModifyTerminal" t="Include">
                <e p="MoveTerminalDescription.vb" t="Include" />
                <e p="RedrawTerminalModule.vb" t="Include" />
                <e p="SwipeTerminalModule.vb" t="Include" />
              </e>
              <e p="TerminalClasses" t="Include">
                <e p="CableClass.vb" t="Include" />
                <e p="JumperClass.vb" t="Include" />
                <e p="LevelTerminalClass.vb" t="Include" />
                <e p="TerminalClass.vb" t="Include" />
                <e p="TerminalDictionaryClass.vb" t="Include" />
                <e p="TerminalStripClass.vb" t="Include" />
                <e p="WireClass.vb" t="Include" />
              </e>
              <e p="TerminalEnums" t="Include">
                <e p="EnumDescriptor.vb" t="Include" />
                <e p="EnumDescriptorCollection.vb" t="Include" />
                <e p="EnumFunctions.vb" t="Include" />
                <e p="TerminalEnums.vb" t="Include" />
              </e>
              <e p="TerminalForms" t="Include">
                <e p="ufTagChanger.Designer.vb" t="Include" />
                <e p="ufTagChanger.resx" t="Include" />
                <e p="ufTagChanger.vb" t="Include" />
                <e p="ufTerminalSelector.Designer.vb" t="Include" />
                <e p="ufTerminalSelector.resx" t="Include" />
                <e p="ufTerminalSelector.vb" t="Include" />
                <e p="ufTerminalTypeSelector.Designer.vb" t="Include" />
                <e p="ufTerminalTypeSelector.resx" t="Include" />
                <e p="ufTerminalTypeSelector.vb" t="Include" />
              </e>
              <e p="TerminalModules" t="Include">
                <e p="AddJumpers.vb" t="Include" />
                <e p="AddressMarkingModule.vb" t="Include" />
                <e p="AddTerminalAccessories.vb" t="Include" />
                <e p="DrawBlocks.vb" t="Include" />
                <e p="DrawLayerChecker.vb" t="Include" />
                <e p="TagChangerModule.vb" t="Include" />
                <e p="TerminalClassMapping.vb" t="Include" />
              </e>
            </e>
          </e>
        </e>
      </e>
      <e p="AutoCADElectrical.sln" t="IncludeFlat" />
      <e p="packages" t="ExcludeRecursive" />
    </e>
    <e p="D:\Autocad Additional Files\AcadApplications\dotNET\Projects\AutoCADElectricalSpecifications\AutoCADElectricalSpecifications" t="IncludeRecursive">
      <e p="app.config" t="Include" />
      <e p="AutoCADElectricalSpecifications.vbproj" t="IncludeRecursive" />
      <e p="bin" t="ExcludeRecursive" />
      <e p="eknis_asu_default_catDataSet.Designer.vb" t="Include" />
      <e p="eknis_asu_default_catDataSet.xsc" t="Include" />
      <e p="eknis_asu_default_catDataSet.xsd" t="Include" />
      <e p="eknis_asu_default_catDataSet.xss" t="Include" />
      <e p="GlobalSuppressions.vb" t="Include" />
      <e p="My Project" t="Include">
        <e p="Application.Designer.vb" t="Include" />
        <e p="Application.myapp" t="Include" />
        <e p="AssemblyInfo.vb" t="Include" />
        <e p="Resources.Designer.vb" t="Include" />
        <e p="Resources.resx" t="Include" />
        <e p="Settings.Designer.vb" t="Include" />
        <e p="Settings.settings" t="Include" />
      </e>
      <e p="obj" t="ExcludeRecursive" />
      <e p="packages.config" t="Include" />
      <e p="src" t="Include">
        <e p="com" t="Include">
          <e p="vasilchenko" t="Include">
            <e p="Classes" t="Include">
              <e p="CableItem.vb" t="Include" />
              <e p="DrawingSpecificationItem.vb" t="Include" />
              <e p="ListViewColumnSorter.vb" t="Include" />
            </e>
            <e p="Commands.vb" t="Include" />
            <e p="DatabaseConnection" t="Include">
              <e p="DatabaseConnections.vb" t="Include" />
              <e p="DatabaseDataAccessObject.vb" t="Include" />
            </e>
            <e p="Forms" t="Include">
              <e p="PageSelector.Designer.vb" t="Include" />
              <e p="PageSelector.resx" t="Include" />
              <e p="PageSelector.vb" t="Include" />
              <e p="ufSpecSelector.Designer.vb" t="Include" />
              <e p="ufSpecSelector.resx" t="Include" />
              <e p="ufSpecSelector.vb" t="Include" />
            </e>
            <e p="Modules" t="Include">
              <e p="AdditionalFunctions.vb" t="Include" />
              <e p="CableTableDrawing.vb" t="Include" />
              <e p="ItemListMaker.vb" t="Include" />
              <e p="KDTableDrawing.vb" t="Include" />
              <e p="KDTableUpdater.vb" t="Include" />
              <e p="PageListMaker.vb" t="Include" />
              <e p="PageTableDrawing.vb" t="Include" />
              <e p="PageTableUpdater.vb" t="Include" />
              <e p="ProjectTableDrawing.vb" t="Include" />
            </e>
          </e>
        </e>
      </e>
    </e>
    <e p="D:\Autocad Additional Files\AcadApplications\dotNET\Projects\AutoCADVBNETLayoutCreator\AutoCADVBNETLayoutCreator" t="IncludeRecursive">
      <e p="AutoCADVBNETLayoutCreator.vbproj" t="IncludeRecursive" />
      <e p="bin" t="ExcludeRecursive" />
      <e p="My Project" t="Include">
        <e p="Application.Designer.vb" t="Include" />
        <e p="Application.myapp" t="Include" />
        <e p="AssemblyInfo.vb" t="Include" />
        <e p="Resources.Designer.vb" t="Include" />
        <e p="Resources.resx" t="Include" />
        <e p="Settings.Designer.vb" t="Include" />
        <e p="Settings.settings" t="Include" />
      </e>
      <e p="obj" t="ExcludeRecursive" />
      <e p="src" t="Include">
        <e p="com" t="Include">
          <e p="vasilchenko" t="Include">
            <e p="Classes" t="Include">
              <e p="PrintedPoligon.vb" t="Include" />
            </e>
            <e p="Commands.vb" t="Include" />
            <e p="Forms" t="Include">
              <e p="LayerSelector.Designer.vb" t="Include" />
              <e p="LayerSelector.resx" t="Include" />
              <e p="LayerSelector.vb" t="Include" />
              <e p="StartForm.Designer.vb" t="Include" />
              <e p="StartForm.resx" t="Include" />
              <e p="StartForm.vb" t="Include" />
            </e>
            <e p="Modules" t="Include">
              <e p="LayoutsCreator.vb" t="Include" />
              <e p="PolygonsConfigurator.vb" t="Include" />
            </e>
          </e>
        </e>
      </e>
    </e>
  </component>
</project>